---
title: "RM04 - Projet n°2"
author: "Baptiste Toussaint"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
    toc_depth: 4
  word_document:
    toc: true
    toc_depth: '4'
---

```{r setup, include=FALSE}
# Chunk de code utile pour la compilation du markdown
knitr::opts_chunk$set(echo = TRUE,
                      cache = TRUE,
                      fig.align='center')

# pour faciliter la compilation
rm(list=ls())

# chargement des librairies utiles que j'aime utiliser dans mes projets
# je détaille les fonctions utilisées si nécessaires
library(readxl)
library(magrittr)
library(ggplot2)
library(stringr)
library(scales)
library(dplyr)
```

```{r message=FALSE, warning=FALSE}
# thème personnel pour mes graphiques
custom_theme <- theme(
        panel.background = element_rect(fill = "#D9E8F1",
                                        colour = "#6D9EC1",
                                        size = 1, linetype = "solid")
)
```

```{r}
# récupération des données depuis le document excel
df <- readxl::read_xlsx("data/Historique panne.xlsx")
# le symbole '%>%' est nommé 'pipe' et signifie : passer en argument
# ici je passe le dataframe df en argument à la fonction `head()` pour
# afficher les premières colonnes.
df %>% head()
```

```{r child = './src/parts/intro.Rmd'}

```


```{r child = './src/parts/classification_ABC.Rmd'}

```

```{r child = './src/parts/estimations.Rmd'}

```

```{r child = './src/parts/optimisation_classe_A.Rmd}

```

```{r child = './src/parts/optimisation_classe_A.Rmd}

```
